### ISSUE TITLE
trouble subscribing to PVs (channel access) after upgrade

### ISSUE THREAD

**Issue by tynanford** [ornl-epics/pvws#9]
I was running pvws commit 4af7c9a017042dd090642b03f9e8b61bdee3a3c2 and tried to upgrade to the latest master branch commit.

I see the correct addr list and other settings printed out.

```
dbwr-test    | 2022-05-18 16:04:22 INFO [pvws.ws] ===========================================
dbwr-test    | 2022-05-18 16:04:22 INFO [pvws.ws] /pvws started
dbwr-test    | 2022-05-18 16:04:22 INFO [pvws.ws] Environment:
dbwr-test    | EPICS_CA_ADDR_LIST = <expected addr list is here>
dbwr-test    | EPICS_CA_MAX_ARRAY_BYTES = null
dbwr-test    | PV_THROTTLE_MS = 1000
dbwr-test    | PV_ARRAY_THROTTLE_MS = 10000
dbwr-test    | PV_WRITE_SUPPORT = false
dbwr-test    | 2022-05-18 16:04:22 INFO [pvws.ws] ===========================================
```
I noticed the JCA addr list is blank

```
dbwr-test    | 18-May-2022 16:04:22.412 INFO [main] org.apache.catalina.startup.Catalina.start Server startup in [1378] milliseconds
dbwr-test    | 2022-05-18 16:04:31 INFO [pvws.ws] PV_THROTTLE_MS = 1000
dbwr-test    | 2022-05-18 16:04:31 INFO [pvws.ws] PV_ARRAY_THROTTLE_MS = 10000
dbwr-test    | 2022-05-18 16:04:31 INFO [pvws.ws] PV_WRITE_SUPPORT = false
dbwr-test    | 2022-05-18 16:04:31 INFO [java.util.prefs] Created user preferences directory.
dbwr-test    | 2022-05-18 16:04:31 INFO [org.phoebus.pv] Default PV type ca://
dbwr-test    | 2022-05-18 16:04:44 INFO [org.phoebus.pv] JCA addr_list: 
```

And I notice that none of my PVs seem to connect (simulated PVs work as expected). A subscribe message for a PV returns this with no values.

```
{
  "pv": "<pvname>",
  "readonly": true,
  "type": "update"
}
```

Thanks!

**Comment by kasemir** [comment]
Could be a result of changing from the internal copy of core-pv to using the released maven binary.
Need to look at it.
Where are you setting EPICS_CA_ADDR_LIST?  $CATALINA_HOME/bin/setenv.sh, tomcat.conf, ..?

**Comment by tynanford** [comment]
I am setting it in $CATALINA_HOME/bin/setenv.sh

You can look at my very crude docker file here: https://github.com/tynanford/dbwr-docker/blob/master/config/Dockerfile

I can confirm that this dockerfile works with the old commit I was on but doesn't work when I switch to the latest master commit.

**Comment by tynanford** [comment]
Well let me amend this - "I can confirm that this dockerfile works with the old commit I was on but doesn't work when I switch to the latest master commit."

With the previous commit my dockerfile is different and is using ant instead of maven. So I am using this Dockerfile: https://github.com/tynanford/dbwr-docker/blob/master/config/Dockerfile.ant

**Comment by kasemir** [comment]
In short, you need to set the Java property "jca.use_env" to "true" and then ignore the "JCA addr_list: <nothing>" printout.

Setting that property causes JCA to use the EPICS_CA_ADDR_LIST environment  variable, ignoring the various system properties that core-pv sets based on preferences.
I'll update the PVWS so it sets "jca.use_env", and core-pv so it skips the property/preference gymnastics.

**Comment by kasemir** [comment]
PVWS has been updated to set "jca.use_env" to "true", so EPICS_CA_ADDR_LIST is again used.

There's an update to core-pv to remove the  "JCA addr_list: " printout, instead showing EPICS_CA_ADDR_LIST when "jca.use_env" is "true". But since that's now fetched from maven, the following needs to happen:

1) https://github.com/ControlSystemStudio/phoebus/pull/2264 gets merged
2) New phoebus release
3) PVWS pom.xml updated to use the new release of core-pv

Meanwhile, it already "works", thanks for finding this issue!

**Comment by tynanford** [comment]
Thanks Kay, much appreciated. I tried it out and now get this error whenever I try to subscribe to any PVs:

```
dbwr    | 2022-05-18 20:54:51 INFO [pvws.ws] PV_THROTTLE_MS = 1000
dbwr    | 2022-05-18 20:54:51 INFO [pvws.ws] PV_ARRAY_THROTTLE_MS = 10000
dbwr    | 2022-05-18 20:54:51 INFO [pvws.ws] PV_WRITE_SUPPORT = false
dbwr    | 2022-05-18 20:54:51 INFO [java.util.prefs] Created user preferences directory.
dbwr    | 2022-05-18 20:54:51 INFO [org.phoebus.pv] Default PV type ca://
dbwr    | 2022-05-18 20:54:51 INFO [org.phoebus.pv] JCA addr_list: 
dbwr    | 2022-05-18 20:54:51 WARNING [org.phoebus.pv] Cannot create PV 'cmm:beam_current'
dbwr    | java.lang.NumberFormatException: For input string: ""
dbwr    | 	at java.base/java.lang.NumberFormatException.forInputString(NumberFormatException.java:67)
dbwr    | 	at java.base/java.lang.Integer.parseInt(Integer.java:670)
dbwr    | 	at java.base/java.lang.Integer.parseInt(Integer.java:778)
dbwr    | 	at com.cosylab.epics.caj.CAJContext.loadConfiguration(CAJContext.java:461)
dbwr    | 	at com.cosylab.epics.caj.CAJContext.<init>(CAJContext.java:352)
dbwr    | 	at org.phoebus.pv.ca.JCAContext.<init>(JCAContext.java:45)
dbwr    | 	at org.phoebus.pv.ca.JCAContext.getInstance(JCAContext.java:77)
dbwr    | 	at org.phoebus.pv.ca.JCA_PV.createChannel(JCA_PV.java:162)
dbwr    | 	at org.phoebus.pv.ca.JCA_PV.<init>(JCA_PV.java:154)
dbwr    | 	at org.phoebus.pv.ca.JCA_PVFactory.createPV(JCA_PVFactory.java:30)
dbwr    | 	at org.phoebus.pv.PVPool.createPV(PVPool.java:136)
dbwr    | 	at org.phoebus.pv.PVPool.lambda$getPV$0(PVPool.java:127)
dbwr    | 	at org.phoebus.pv.RefCountMap.createOrGet(RefCountMap.java:102)
dbwr    | 	at org.phoebus.pv.PVPool.getPV(PVPool.java:127)
dbwr    | 	at pvws.ws.WebSocketPV.start(WebSocketPV.java:93)
dbwr    | 	at pvws.ws.WebSocket.lambda$onMessage$9(WebSocket.java:307)
dbwr    | 	at java.base/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1708)
dbwr    | 	at pvws.ws.WebSocket.onMessage(WebSocket.java:301)
dbwr    | 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
dbwr    | 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
dbwr    | 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
dbwr    | 	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
dbwr    | 	at org.apache.tomcat.websocket.pojo.PojoMessageHandlerWholeBase.onMessage(PojoMessageHandlerWholeBase.java:104)
dbwr    | 	at org.apache.tomcat.websocket.WsFrameBase.sendMessageText(WsFrameBase.java:415)
dbwr    | 	at org.apache.tomcat.websocket.server.WsFrameServer.sendMessageText(WsFrameServer.java:129)
dbwr    | 	at org.apache.tomcat.websocket.WsFrameBase.processDataText(WsFrameBase.java:515)
dbwr    | 	at org.apache.tomcat.websocket.WsFrameBase.processData(WsFrameBase.java:301)
dbwr    | 	at org.apache.tomcat.websocket.WsFrameBase.processInputBuffer(WsFrameBase.java:133)
dbwr    | 	at org.apache.tomcat.websocket.server.WsFrameServer.onDataAvailable(WsFrameServer.java:85)
dbwr    | 	at org.apache.tomcat.websocket.server.WsFrameServer.doOnDataAvailable(WsFrameServer.java:183)
dbwr    | 	at org.apache.tomcat.websocket.server.WsFrameServer.notifyDataAvailable(WsFrameServer.java:162)
dbwr    | 	at org.apache.tomcat.websocket.server.WsHttpUpgradeHandler.upgradeDispatch(WsHttpUpgradeHandler.java:157)
dbwr    | 	at org.apache.coyote.http11.upgrade.UpgradeProcessorInternal.dispatch(UpgradeProcessorInternal.java:60)
dbwr    | 	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:59)
dbwr    | 	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:890)
dbwr    | 	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1743)
dbwr    | 	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
dbwr    | 	at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191)
dbwr    | 	at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
dbwr    | 	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
dbwr    | 	at java.base/java.lang.Thread.run(Thread.java:831)
dbwr    | 
dbwr    | 2022-05-18 20:54:51 WARNING [pvws.ws] Cannot start PV cmm:beam_current
dbwr    | java.lang.RuntimeException: Error for PV cmm:beam_current
dbwr    | 	at org.phoebus.pv.RefCountMap.createOrGet(RefCountMap.java:112)
dbwr    | 	at org.phoebus.pv.PVPool.getPV(PVPool.java:127)
dbwr    | 	at pvws.ws.WebSocketPV.start(WebSocketPV.java:93)
dbwr    | 	at pvws.ws.WebSocket.lambda$onMessage$9(WebSocket.java:307)
dbwr    | 	at java.base/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1708)
dbwr    | 	at pvws.ws.WebSocket.onMessage(WebSocket.java:301)
dbwr    | 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
dbwr    | 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
dbwr    | 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
dbwr    | 	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
dbwr    | 	at org.apache.tomcat.websocket.pojo.PojoMessageHandlerWholeBase.onMessage(PojoMessageHandlerWholeBase.java:104)
dbwr    | 	at org.apache.tomcat.websocket.WsFrameBase.sendMessageText(WsFrameBase.java:415)
dbwr    | 	at org.apache.tomcat.websocket.server.WsFrameServer.sendMessageText(WsFrameServer.java:129)
dbwr    | 	at org.apache.tomcat.websocket.WsFrameBase.processDataText(WsFrameBase.java:515)
dbwr    | 	at org.apache.tomcat.websocket.WsFrameBase.processData(WsFrameBase.java:301)
dbwr    | 	at org.apache.tomcat.websocket.WsFrameBase.processInputBuffer(WsFrameBase.java:133)
dbwr    | 	at org.apache.tomcat.websocket.server.WsFrameServer.onDataAvailable(WsFrameServer.java:85)
dbwr    | 	at org.apache.tomcat.websocket.server.WsFrameServer.doOnDataAvailable(WsFrameServer.java:183)
dbwr    | 	at org.apache.tomcat.websocket.server.WsFrameServer.notifyDataAvailable(WsFrameServer.java:162)
dbwr    | 	at org.apache.tomcat.websocket.server.WsHttpUpgradeHandler.upgradeDispatch(WsHttpUpgradeHandler.java:157)
dbwr    | 	at org.apache.coyote.http11.upgrade.UpgradeProcessorInternal.dispatch(UpgradeProcessorInternal.java:60)
dbwr    | 	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:59)
dbwr    | 	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:890)
dbwr    | 	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1743)
dbwr    | 	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
dbwr    | 	at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191)
dbwr    | 	at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
dbwr    | 	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
dbwr    | 	at java.base/java.lang.Thread.run(Thread.java:831)
dbwr    | Caused by: java.lang.NullPointerException
dbwr    | 	at java.base/java.util.Objects.requireNonNull(Objects.java:208)
dbwr    | 	at org.phoebus.pv.RefCountMap$ReferencedEntry.<init>(RefCountMap.java:40)
dbwr    | 	at org.phoebus.pv.RefCountMap.createOrGet(RefCountMap.java:102)
dbwr    | 	... 28 more
dbwr    | 
```

**Comment by kasemir** [comment]
CAJContext.java:461 is this:
```
tmp = System.getenv("EPICS_CA_MAX_ARRAY_BYTES");
if (tmp != null) maxArrayBytes = Integer.parseInt(tmp);
```

Is it possible that you have EPICS_CA_MAX_ARRAY_BYTES defined but empty?
I think I have it set to 1000000, i.e. defined with a numeric value.
